module.exports.recipes=[
    {
        name: 'Shortcrust pastry for Handpies',
        photo: 'images/louis-hansel-LIJujhJviMI-unsplash.jpg',
        ingredients: [
            '1 7/8 cups all purpose flour', 
            '1/2 tsp salt',
            '1/4 cup cold butter',
            '1/4 cup lard',
            '1/2 cup ice water'],
        directions: [
            'Pulse flour and salt together in food processor',
            'Add butter and lard to food processor, pulse until until only chickpea-sized pieces remain', 
            'Add water gradually while pulsing until the dough just jholds together when pressed with hands',
            'Refrigerate dough in plastic until read to use'],
        notes: 'Recipe was modified to account for the small size of my food processor.',
        tags: ['Make-ahead']
    },
    {
        name: 'Tourtiere Handpie Filling',
        photo: 'images/louis-hansel-LIJujhJviMI-unsplash.jpg',
        ingredients: [
            '1/2 kg of pork',
            '1/2 kg of beef',
            '1 1/2 cups cold water',
            '1 cup finely chopped onion',
            '1/2 cup finely chopped celery',
            '2 tsp black pepper',
            '3 bay leaves',
            '2 tsp dried savory',
            '1 tsp dried rosemary',
            '1 tsp grated nutmeg',
            '1 tsp cinnamon',
            'salt to taste',
            '1/2 cup old-fashioned rolled oats'],
        directions: [
            'In large pot, combine meat with cold water and heat to boiling point',
            'Add onion, celery, and herbs and spice. Cook covered over medium-low heat for 1 1/4 hours, stirring occasionally. Add more water if mixture dried out',
            'Stir in rolled oats and cook for 1-2 minutes',
            'Remove bay leaves and allow to cool',
            'Fill prepared pastry with tourtiere filling',
            'Bake in oven at 400F for 45 minutes for handpies. For a full pie, bake at 425 F for 15 minutes, then reduce heat to 375 F for another 25 minutes, or until crust is golden'],
        notes: 'Recipe was modified to account for the small size of my food processor.',
        tags: ['Pastry', 'Make-ahead']
    },
    {
        name: 'Beef and Barley Stew',
        photo: 'images/louis-hansel-LIJujhJviMI-unsplash.jpg',
        ingredients: [
            '1 family sized pack of stewing beef, divided in half',
            '3-4 large chopped carrots',
            '1 chopped onion',
            '3/4 cups chopped celery',
            '5 cups water',
            '1 tsp parsley flakes',
            '1/4 tsp pepper',
            '1 tsp sugar',
            '3 beef stock cubes',
            '1/2 cup pearl barley',
            '15 oz can of tomato sauce'],
        directions: [
            'Cut the stewing beef into smaller, bite-sized bits. Set aside half of a family-sized package of meat for another batch of beef stew.',
            'PLace all ingredients in a slow cooker',
            'Stir it up',
            'Cover and cook on low for 8-10 hours or on high for 4-5 hours'],
        notes: 'You use three stock cubes per batch, original recipe called for 2 TBSP stock powder',
        tags: ['Slowcooker', 'Make-ahead']
    },
    {
        name: 'Breakfast Cookies',
        photo: 'images/louis-hansel-LIJujhJviMI-unsplash.jpg',
        ingredients: [
            '1/2 cup butter',
            '1/3 cup brown sugar, heaping',
            '1/4 tsp salt',
            '1/2 tsp baking soda',
            '2 eggs',
            'splash of vanilla',
            '1/4 cup oil',
            '1/4 cup bran',
            '1/2 cup ground flax seed',
            '3 tbsp chia seed',
            '1 tbsp chocolate chips',
            '1 1/5 cups whole wheat flour',
            '1 1/2 cups old-fashioned rolled oats'],
        directions: [
            'Beat softened butter and sugar together until fluffy',
            'Add eggs, oil, and vanilla to mix',
            'Add flax seed, chia seed, bran, salt, and baking soda',
            'Add flour gradually while mixing, careful not to overmix',
            'Add chocolate chips and oats',
            'Roll into 20 small balls',
            'Bake at 375 for 15 minutes'],
        notes: 'Modified from an oatmeal cookie recipe. Feel free to add a drizzle of maple syrup for extra sweetness',
        tags: ['Breakfast', 'Make-ahead']
    },
    {
        name: 'Brownies',
        photo: 'images/louis-hansel-LIJujhJviMI-unsplash.jpg',
        ingredients: [
            '1/2 cup + 2 tbsp salted butter, melted', 
            '1 cup granulated sugar',
            '2 large eggs',
            '2 tsp vanilla extract',
            '1/2 cup melted chocolate chips',
            '3/4 cups all-purpose flour',
            '1/4 cup unsweetened cocoa powder',
            '1/2 tsp salt',
            '1 cup milk chocolate chips'],
        directions: [
            'Preheat oven to 350 F. Line a metal 9x9 pan with parchement paper.',
            'Pour melted butter into a large mixing bowl. Whisk in sugar by hand until smooth, 30 seconds.',
            'Add in eggs and vanilla extract. Whisk 1 minute.',
            'Whisk in melted chocolate until combined and smooth.',
            'Use a rubber spatula to stir in flour, cocoa powder, and salt until just combined. Stir in whole chocolate chips.',
            'Pour into prepared pan and smooth out.',
            'Bake in the preheated oven for 30 minutes. Let cool in pan 30 minutes before slicing.'],
        notes: 'Recipe was modified to account for the small size of my food processor.',
        tags: ['Dessert']
    },
]